apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    NAME: rabbitmq1
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: yc-rabbit
  name: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: yc-rabbit
  strategy: {}
  template:
    metadata:
      annotations:
        NAME: rabbitmq1
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 (992df58d8)
      labels:
        date: "{{ now | unixEpoch }}"
        io.kompose.network/rabbitmq: "true"
        io.kompose.service: yc-rabbit
    spec:
      securityContext:
        fsGroup: {{ .Values.YANG_GID }}
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: yangcatalog-secret
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: yangcatalog-secret
              key: RABBITMQ_USER
        - name: RABBITMQ_DEFAULT_VHOST
          value: /
        - name: RABBITMQ_ERLANG_COOKIE
          value: SWQOKODSQALRPCLNMEQG
        image: rabbitmq:3-management
        name: rabbit
      restartPolicy: Always
