apiVersion: v1
kind: PersistentVolume
metadata:
  name: docs-pv
spec:  
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
    name: docs-pvc
    namespace: default
  local:
    path: {{ .Values.YANG_VOLUMES }}/docs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.K8S_FILESYSTEM_NODE }}
