apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: run-pvc
  name: run-pvc
spec:
  storageClassName: "local-storage"
  volumeName: run-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
