apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: yc-confd
  name: confd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: yc-confd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.network/confd: "true"
        io.kompose.service: yc-confd
    spec:
      securityContext:
        fsGroup: {{ .Values.YANG_GID }}
      containers:
      - image: {{ .Values.DOCKER_REGISTRY }}/yc_confd:latest
        imagePullPolicy: {{ .Values.IMAGE_PULL_POLICY }}
        name: confd
        ports:
        - containerPort: 8008
        - containerPort: 8888
        volumeMounts:
        - mountPath: /a/system/yangcatalog.org.key
          name: key-file-pv
        - mountPath: /a/system/yangcatalog.org.crt
          name: cert-file-pv
        - mountPath: /var/yang/logs
          name: confd-log-pv
      restartPolicy: Always
      volumes:
      - name: key-file-pv
        hostPath:
          path: {{ .Values.KEY_FILE }}
      - name: cert-file-pv
        hostPath:
          path: {{ .Values.CERT_FILE }}
      - name: confd-log-pv
        hostPath:
          path: {{ .Values.CONFD_LOG }}
