apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: admin-ui
  name: admin-ui
spec:
  backoffLimit: 6
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 (992df58d8)
      labels:
        date: "{{ now | unixEpoch }}"
        io.kompose.network/frontend: "true"
        io.kompose.service: admin-ui
    spec:
      securityContext:
        fsGroup: {{ .Values.YANG_GID }}
      containers:
      - image: {{ .Values.DOCKER_REGISTRY }}/yc_admin-ui:latest
        imagePullPolicy: {{ .Values.IMAGE_PULL_POLICY }}
        name: admin-ui
        volumeMounts:
        - mountPath: /usr/share/nginx/html/admin
          name: admin-webroot-pv
        - mountPath: /var/yang
          name: yang-resources-pv
      restartPolicy: OnFailure
      volumes:
      - name: admin-webroot-pv
        persistentVolumeClaim:
          claimName: admin-webroot-pvc
      - name: yang-resources-pv
        hostPath:
          path: {{ .Values.YANG_RESOURCES }}
