apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: celery-worker
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery-worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.network/backend: "true"
        io.kompose.network/confd: "true"
        io.kompose.network/rabbitmq: "true"
        io.kompose.network/opensearch: "true"
        io.kompose.network/redis: "true"
        io.kompose.network/tools-ieft-org: "true"
        io.kompose.network/rsync: "true"
        io.kompose.service: celery-worker
    spec:
      securityContext:
        fsGroup: {{ .Values.YANG_GID }}
        runAsUser: {{ .Values.YANG_ID }}
        runAsGroup: {{ .Values.YANG_GID }}
      containers:
      - image: {{ .Values.DOCKER_REGISTRY }}/catalog_backend_api:latest
        imagePullPolicy: {{ .Values.IMAGE_PULL_POLICY }}
        name: celery-worker
        command: ["/bin/bash"]
        args: ["-c", "chown -R yang:yang /var/run/yang; service postfix start; celery -A jobs.celery:celery_app worker -l INFO"]
        volumeMounts:
        - mountPath: /etc/yangcatalog/yangcatalog.conf
          name: yangcatalog-conf-pv
          readOnly: true
        - mountPath: /var/yang
          name: yang-resources-pv
        - mountPath: /usr/share/nginx/html/YANG-modules
          name: nginx-yang-modules-pv
        - mountPath: /usr/share/nginx/html/compatibility
          name: nginx-compatibility-pv
        - mountPath: /usr/share/nginx/html/private
          name: nginx-private-pv
        - mountPath: /usr/share/nginx/html/results
          name: nginx-results-pv
        - mountPath: /usr/share/nginx/html/downloadables
          name: downloadables-pv
      restartPolicy: Always
      volumes:
      - name: yangcatalog-conf-pv
        hostPath:
          path: {{ .Values.YANG_RESOURCES }}/conf/yangcatalog.conf
      - name: yang-resources-pv
        hostPath:
          path: {{ .Values.YANG_RESOURCES }}
      - name: nginx-yang-modules-pv
        hostPath:
          path: {{ .Values.YANG_RESOURCES }}/nginx/YANG-modules
      - name: nginx-compatibility-pv
        hostPath:
          path: {{ .Values.YANG_RESOURCES }}/nginx/compatibility
      - name: nginx-private-pv
        hostPath:
          path: {{ .Values.YANG_RESOURCES }}/nginx/private
      - name: nginx-results-pv
        hostPath:
          path: {{ .Values.YANG_RESOURCES }}/nginx/results
      - name: downloadables-pv
        persistentVolumeClaim:
          claimName: downloadables-pvc
